# Generated by Django 2.1.1 on 2018-10-28 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0002_remove_order_sales_rep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DateTimeField()),
                ('quantity_shipped', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_descr', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dept',
            options={'verbose_name': 'Department'},
        ),
        migrations.AddField(
            model_name='dept',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1.Product'),
        ),
    ]
