# Generated by Django 2.1.2 on 2018-10-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0003_auto_20181028_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity_ordered',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity_shipped',
            field=models.IntegerField(),
        ),
    ]
